version: '3.9'

services:
  chatbot:
    build: .
    container_name: chatbot-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # For local development
    env_file:
      - .env
    restart: unless-stopped
